name: Terraform Plan on PR

on:
  pull_request:
    branches:
      - main  # Trigger this workflow when a PR is created against the 'main' branch

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.6  # Adjust based on your Terraform version

    - name: Configure AWS Credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: eu-west-2
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region eu-west-2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Upload Terraform Plan as artifact
      uses: actions/upload-artifact@v2
      with:
        name: terraform-plan
        path: tfplan

    - name: Show Terraform Plan in PR comment
      uses: peter-evans/terraform-comment@v1
      with:
        github_token: ${{ secrets.GB_TOKEN }}  # Ensure the GitHub token variable is correctly defined in your GitHub Secrets
        terraform_plan_path: tfplan

