name: Apply Terraform
on: 
  push:
    branches:
      - 'main'
  
permissions:
  contents: read
  pull-requests: write
  
jobs:
  apply:
    name: Apply Terraform Plan
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: .