name: Terraform plan on PR
on:
  pull_request:
    branches:
      - main  # Trigger this workflow when a PR is created against the 'main' branch
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.6  # Adjust based on your Terraform version
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: eu-west-2
    - name: Terraform Init
      run: terraform init
    - name: Terraform Plan
      run: terraform plan -out=tfplan
    - name: List files (debug step)
      run: ls -l
    - name: Upload Terraform Plan as artifact
      uses: actions/upload-artifact@v4
      with:
        name: terraform-plan
        path: tfplan
    - name: Show Terraform Plan in PR comment
      uses: JosephDucrocq/terraform-comment@v1
      with:
        github_token: ${{ secrets.GB_TOKEN }}
        terraform_plan_path: tfplan